apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: app-a-verification
  namespace: app-a
spec:
  metrics:
    - name: test
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - command:
                      - /bin/sh
                      - -c
                      - exit 1
                    image: alpine:latest
                    name: test
                restartPolicy: Never