apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: 
  promotionPolicies:
  - stage: dev
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
  - stage: region-a-cluster-01
    autoPromotionEnabled: true
  - stage: region-a-cluster-02
    autoPromotionEnabled: true
  - stage: region-a-cluster-03
    autoPromotionEnabled: true