apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: standard-process-prod
  namespace: app-a
spec:
  vars:
  - name: imageRepo
  - name: region
  - name: cluster
  steps:
  - uses: git-clone
    config:
      repoURL: https://github.com/emilyxinyi/kargo-b.git
      checkout:
      - branch: main
        path: ./src
      - branch: app-a/${{ vars.region }}/${{ vars.cluster }}
        create: true
        path: ./out
  - uses: git-clear
    config:
      path: ./out
  - uses: kustomize-set-image
    as: update-image
    config:
      path: ./src/app-a/base
      images:
      - image: ${{ vars.imageRepo }}
        tag: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: kustomize-build
    config:
      path: ./src/app-a/${{ vars.region }}/${{ vars.cluster }}
      outPath: ./out/manifests.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: ${{ task.outputs['update-image'].commitMessage }}
  - uses: git-push
    config:
      path: ./out
      targetBranch: app-a/${{ vars.region }}/${{ vars.cluster }}
  - uses: compose-output
    as: output
    config:
      commit: ${{ task.outputs['commit'].commit }}
  # - uses: argocd-update
  #   config:
  #     apps:
  #     - name: app-a-${{ vars.region }}-${{ vars.cluster }}
  #       sources:
  #       - repoURL: https://github.com/emilyxinyi/kargo-b.git
  #         desiredRevision: ${{ task.outputs.commit.commit }}