apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: standard-process
  namespace: app-a
spec:
  vars:
  - name: imageRepo
  steps:
  - uses: git-clone
    config:
      repoURL: https://github.com/emilyxinyi/kargo-b.git
      checkout:
      - branch: main
        path: ./src
      - branch: app-a/non-prod/${{ ctx.stage }}
        create: true
        path: ./out
  - uses: git-clear
    config:
      path: ./out
  - uses: kustomize-set-image
    as: update-image
    config:
      path: ./src/app-a/non-prod/${{ ctx.stage }}
      images:
      - image: ${{ vars.imageRepo }}
        tag: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: kustomize-build
    config:
      path: ./src/app-a/non-prod/${{ ctx.stage }}
      outPath: ./out/manifests.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: | 
        ${{ ctx.stage }}: ${{ task.outputs['update-image'].commitMessage}}
  - uses: git-push
    config:
      path: ./out
      targetBranch: app-a/non-prod/${{ ctx.stage }}
  - uses: argocd-update
    config:
      apps:
      - name: app-a-non-prod-${{ ctx.stage }}
        sources:
        - repoURL: https://github.com/emilyxinyi/kargo-b.git