apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      steps:
      - task: 
          name: standard-process-non-prod
      - uses: jira
        as: create-deployment-issue
        config:
          credentials:
            secretName: jira-credentials
          createIssue:
            projectKey: SCRUM
            summary: "Deploy ${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }}"
            description: "Deploying ${{ imageFrom(vars.imageRepo).RepoURL }}:${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }} environment. Promotion ID: ${{ ctx.promotion }}. Freight: ${{ ctx.targetFreight.name }}."
            issueType: Task
            # assigneeEmail: devops@company.com
            labels:
              - deployment
              - "${{ ctx.stage }}"
              - "release-${{ imageFrom(vars.imageRepo).Tag }}"
      # # Use the created issue key in subsequent steps
      # - uses: kustomize-set-image
      #   as: failure-simulation
      #   config:
      #     path: invalid
      #     images:
      #     - image: ${{ vars.imageRepo }}
      #       tag: invalid
      # - uses: argocd-update
      #   as: failure-simulation
      #   config:
      #     apps:
      #       - name: test-app
      #         namespace: argocd
      #         sources:
      #         - repoURL: https://github.com/gdsoumya/jira-demo.git
      #           kustomize:
      #             images:
      #             - repoURL: public.ecr.aws/nginx/nginx
      #               tag: ${{ imageFrom("public.ecr.aws/nginx/nginx").Tag }}
      # - uses: jira
      #   as: on-failure-cleanup-issue
      #   if: ${{ failure() }}
      #   # if: ${{ always() }}
      #   config:
      #     credentials:
      #       secretName: jira-credentials
      #     deleteIssue:
      #       # issueKey: "${{ freightMetadata(ctx.targetFreight.name, 'jira-issue-key') }}"
      #       issueKey: ${{ outputs['create-deployment-issue'].key }}
      #       deleteSubtasks: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      steps:
      - uses: jira
        as: add-progress-comment
        config:
          credentials:
            secretName: jira-credentials
          commentOnIssue:
            issueKey: "${{ freightMetadata(ctx.targetFreight.name, 'jira-issue-key') }}"
            body: "Promotion started. Environment: ${{ ctx.stage }}. Image: ${{ imageFrom(vars.imageRepo).RepoURL }}:${{ imageFrom(vars.imageRepo).Tag }}. Promotion: ${{ ctx.promotion }}. Status: Deploying to ${{ ctx.stage }} environment..."
      - task: 
          name: standard-process-non-prod
      - uses: jira
        as: wait-for-status
        config:
          credentials:
            secretName: jira-credentials
          waitForStatus:
            issueKey: "${{ freightMetadata(ctx.targetFreight.name, 'jira-issue-key') }}"
            expectedStatus: "STAGED"
      - uses: jira
        as: delete-progress-comment
        config:
          credentials:
            secretName: jira-credentials
          deleteComment:
            issueKey: "${{ freightMetadata(ctx.targetFreight.name, 'jira-issue-key') }}"
            commentID: "${{ quote(outputs['add-progress-comment'].commentID) }}"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-a-cluster-01
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      - name: region
        value: region-a
      - name: cluster
        value: cluster-01
      steps:
      - task: 
          name: standard-process-prod
        as: promotion
      - uses: jira
        as: search-issue
        config:
          credentials:
            secretName: jira-credentials
          searchIssue:
            jql: "created <= 1d and labels IN (release-${{ imageFrom(vars.imageRepo).Tag }}) ORDER BY created DESC"
            expectMultiple: true
            fields:
              - key
            # Wait for final production approval
      - uses: jira
        as: wait-for-approval
        config:
          credentials:
            secretName: jira-credentials
          waitForStatus:
            issueKey: ${{ outputs['search-issue'].key }}
            expectedStatus: RELEASED
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-a-cluster-01
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-b.git
              desiredRevision: ${{ outputs.promotion.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-a-cluster-02
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-a-cluster-01
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      - name: region
        value: region-a
      - name: cluster
        value: cluster-02
      steps:
      - task: 
          name: standard-process-prod
        as: promotion
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-a-cluster-02
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-b.git
              desiredRevision: ${{ outputs.promotion.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-a-cluster-03
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-a-cluster-01
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      - name: region
        value: region-a
      - name: cluster
        value: cluster-03
      steps:
      - task: 
          name: standard-process-prod
        as: promotion
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-a-cluster-03
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-b.git
              desiredRevision: ${{ outputs.promotion.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-b
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-a-cluster-03
      - region-a-cluster-02
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-b-cluster-01
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-b
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      - name: region
        value: region-b
      - name: cluster
        value: cluster-01
      steps:
      - task: 
          name: standard-process-prod
        as: promotion
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-b-cluster-01
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-b.git
              desiredRevision: ${{ outputs.promotion.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-b-cluster-02
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-b
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      - name: region
        value: region-b
      - name: cluster
        value: cluster-02
      steps:
      - task: 
          name: standard-process-prod
        as: promotion
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-b-cluster-02
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-b.git
              desiredRevision: ${{ outputs.promotion.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-b-cluster-03
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-b
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      - name: region
        value: region-b
      - name: cluster
        value: cluster-03
      steps:
      - task: 
          name: standard-process-prod
        as: promotion
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-b-cluster-03
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-b.git
              desiredRevision: ${{ outputs.promotion.commit }}