apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      steps:
      - task: 
          name: standard-process-non-prod
      - uses: jira
        as: create-deployment-issue
        config:
          credentials:
            secretName: jira-credentials
          createIssue:
            projectKey: SCRUM
            summary: "Deploy ${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }}"
            description: "Deploying ${{ imageFrom(vars.imageRepo).RepoURL }}:${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }} environment. Promotion ID: ${{ ctx.promotion.name }}. Freight: ${{ ctx.targetFreight.name }}."
            issueType: Task
            assigneeEmail: devops@company.com
            labels:
              - deployment
              - "${{ ctx.stage }}"
              - "release-${{ imageFrom(vars.imageRepo).Tag }}"
      # Use the created issue key in subsequent steps
      - uses: jira
        config:
          credentials:
            secretName: jira-credentials
          updateIssue:
            issueKey: "${{ outputs['create-deployment-issue'].key }}"
            status: "IN PROGRESS"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      steps:
      - task: 
          name: standard-process-non-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-a-cluster-01
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/emilyxinyi/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/region-a/cluster-01
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/base
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app-a/region-a/cluster-01
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: ${{ outputs['update-image'].commitMessage }}
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/region-a/cluster-01
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-a-cluster-01
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-b.git
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-a-cluster-02
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-a-cluster-01
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/emilyxinyi/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/region-a/cluster-02
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/base
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app-a/region-a/cluster-02
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: ${{ outputs['update-image'].commitMessage }}
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/region-a/cluster-02
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-a-cluster-02
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-b.git
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-a-cluster-03
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-a-cluster-01
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/emilyxinyi/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/region-a/cluster-03
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/base
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app-a/region-a/cluster-03
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: ${{ outputs['update-image'].commitMessage }}
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/region-a/cluster-03
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-a-cluster-03
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-b.git
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-b
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-a-cluster-03
      - region-a-cluster-02
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-b-cluster-01
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-b
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/emilyxinyi/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/region-b/cluster-01
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/region-b/cluster-01
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app-a/region-b/cluster-01
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: ${{ outputs['update-image'].commitMessage }}
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/region-b/cluster-01
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-b-cluster-01
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-b.git
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-b-cluster-02
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-b
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/emilyxinyi/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/region-b/cluster-02
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/region-b/cluster-02
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app-a/region-b/cluster-02
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: ${{ outputs['update-image'].commitMessage }}
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/region-b/cluster-02
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-b-cluster-02
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-b.git
              desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-b-cluster-03
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-b
  promotionTemplate:
    spec:
      vars: 
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/emilyxinyi/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/region-b/cluster-03
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/region-b/cluster-03
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/app-a/region-b/cluster-03
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: ${{ outputs['update-image'].commitMessage }}
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/region-b/cluster-03
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-b-cluster-03
            sources:
            - repoURL: https://github.com/emilyxinyi/kargo-b.git
              desiredRevision: ${{ outputs.commit.commit }}