apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-app-a
spec:
  project: kargo-b-demo
  source:
    repoURL: https://github.com/dhpup/kargo-b.git
    path: kargo-app-a
  destination:
    server: https://b5bxdj947v9xturb-cplane.kargosvcs.akuity.cloud
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
